name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.0
      with: 
        node-version: 12.x

    - name: Install dependencies
      run: npm ci
      
    - name: Set private key
      env:
          SSH_PRIVATE_KEY: ${{SSH_PRIVATE_KEY}}
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        
    - name: Setup Git Infomation
      run: | 
        git config --global user.name 'DavidZ' 
        git config --global user.email 'davidbill@outlook.com'
        
    - name: Deploy
      run: |
        node ./tools/deploy-with-scp.js
